name: Automatic Issue Transition

on:
  issues:
    types: [closed]

jobs:
  automate_issue_transition:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue is labeled "In Progress"
        run: |
          # Extract the labels of the closed issue
          labels=$(echo "${{ github.event.issue.labels }}" | jq -r '.[] | .name')
          # Check if the "In Progress" label is present
          if [[ $labels =~ "In Progress" ]]; then
            # If it is, remove the "In Progress" label and add the "Review" label
            curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/In%20Progress"
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"labels": ["Review"]}' "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
